services:
  db:
    image: postgres:14
    container_name: openquiz-database
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database/scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 5s
      timeout: 5s
      retries: 5